name: "Daily Build"
on:
  schedule:
    - cron: '* * * * *'
jobs:
  strelka:
    name: "Strelka UI Daily Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka UI
        run: docker-compose build
